services:
  # APIサーバー - ユーザーデータやステータス情報の処理
  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/gamification
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  # ワーカー - 非同期処理を担当
  worker:
    build:
      context: ./backend/worker
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/gamification
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network

  # PostgreSQLデータベース - ユーザーや企業情報の保存
  postgres:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    volumes:
      - ./backend/database/init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gamification
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # フロントエンド - Reactアプリケーション
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=pepa_linha
      - SERVER=postgres
    ports:
      - 5050:8080
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge