blank_issues_enabled: false
contact_links:
  # - name: 質問・相談
  #   url: https://github.com/nogikun/Gamification-for-factory/issues
  #   about: バグ報告や機能リクエスト以外の質問・相談はDiscussionsをご利用ください。

# Issue作成時のテンプレート設定
defaults:
  - template: "bug_report.yml"
    name: "🐛 バグ報告"
    about: "バグを報告する"
  - template: "add_feature_task.yml"
    name: "💡 Featureタスク設定"
    about: "機能開発のタスクを設定する"
  - template: "add_development_task.yml"
    name: "💻 Developmentタスクを設定する"
    about: "開発タスクを定義する"
# Copyright (c) 2025 nogi
# All rights reserved.
