-- Initial Data Insertion for Gamification for Factory Human Resource Development

-- General Note:
-- IDs for SERIAL or BIGSERIAL columns are auto-generated by PostgreSQL.
-- For simplicity in this seed script, we will assume certain auto-generated IDs
-- for foreign key references. In a real application, these might be fetched
-- dynamically or handled by application logic after insertion.
-- Passwords shown are placeholders and should be replaced with actual cryptographically hashed passwords.

-- 1. Administrator User
-- Password: '[YOUR_HASHED_ADMIN_PASSWORD_HERE]' (replace with actual hash)
INSERT INTO users (full_name, email, password_hash, user_type, is_active) VALUES
('Admin User', 'admin@example.com', '$2b$12$abcdefghijklmnopqrstuv.ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijkl', 'admin', TRUE);
-- Assume admin_user_id = 1 after this insertion.

-- 2. Badge Master Data
INSERT INTO badge_masters (badge_name, description, icon_url, acquisition_criteria_summary, skill_category_related, is_active) VALUES
('Lathe Operation Basics', 'Awarded for mastering basic lathe operations.', 'https://example.com/icons/lathe_beginner.png', 'Completion of Task A in Internship Alpha', 'Lathe Skills', TRUE),
('Communication Leader', 'Recognizes proactive and effective team communication.', 'https://example.com/icons/communication_leader.png', 'Demonstrated leadership in group project Beta', 'Communication', TRUE),
('Safety First Award', 'Awarded for maintaining excellent safety standards.', 'https://example.com/icons/safety_first.png', 'No safety incidents for 3 consecutive months and passing safety quiz.', 'Safety', TRUE),
('CNC Programming Introduction', 'Awarded for completing introductory CNC programming module.', 'https://example.com/icons/cnc_intro.png', 'Successful completion of CNC module tasks.', 'CNC Programming', TRUE);

-- 3. Sample Job Seeker Users
-- Passwords: '[HASHED_PASSWORD]' (replace with actual hashes)
INSERT INTO users (full_name, email, password_hash, user_type, profile_summary, is_active) VALUES
('Hana Jobseeker', 'seeker1@example.com', '$2b$12$abcdefghijklmnopqrstuv.ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijkl', 'job_seeker', 'Interested in manufacturing! Especially keen on learning metalworking.', TRUE),
('Jiro Jobseeker', 'seeker2@example.com', '$2b$12$abcdefghijklmnopqrstuv.ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijkl', 'job_seeker', 'Excited about the intersection of programming and machinery.', TRUE),
('Saburo Jobseeker', 'seeker3@example.com', '$2b$12$abcdefghijklmnopqrstuv.ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijkl', 'job_seeker', 'Eager to learn about quality control and process improvement.', TRUE);
-- Assume job_seeker_ids might be 2, 3, 4

-- 4. Sample Company Representative Users
-- Passwords: '[HASHED_PASSWORD]' (replace with actual hashes)
INSERT INTO users (full_name, email, password_hash, user_type, is_active) VALUES
('Ichiro CompanyRep', 'comprep1@example.com', '$2b$12$abcdefghijklmnopqrstuv.ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijkl', 'company_representative', TRUE),
('Futami CompanyRep', 'comprep2@example.com', '$2b$12$abcdefghijklmnopqrstuv.ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijkl', 'company_representative', TRUE);
-- Assume company_representative_user_ids might be 5, 6

-- 5. Sample Company Information
-- For these inserts, we assume:
-- - Admin User ID = 1
-- - Ichiro CompanyRep (for Sample A Manufacturing Co.) User ID = 5 (MUST be 'company_representative')
-- - Futami CompanyRep (for Sample B Tech Solutions) User ID = 6 (MUST be 'company_representative')

-- Company A
INSERT INTO companies (
    representative_user_id,
    company_name,
    industry,
    location,
    website_url,
    description,
    pr_message,
    logo_image_url,
    contact_email,
    contact_phone,
    approval_status,
    approved_by_admin_id,
    approved_at
) VALUES (
    5, -- Assuming Ichiro CompanyRep user_id is 5
    'Sample A Manufacturing Co.',
    'Manufacturing',
    'Osaka, Japan',
    'https://sampleA.example.com',
    'Specializing in precision metal parts.',
    'We focus on nurturing young talent! Improve your skills with our modern equipment.',
    'https://example.com/logos/sampleA.png',
    'contact@sampleA.example.com',
    '06-1234-5678',
    'approved',
    1, -- Assuming Admin User ID is 1
    NOW()
);
-- Assume company_id for Sample A Manufacturing Co. is 1

-- Update users.company_id for Ichiro CompanyRep (user_id=5) with company_id for Sample A (company_id=1)
-- This would typically be handled by application logic after company registration.
-- For seeding purposes, if company_id is known/assumed:
UPDATE users SET company_id = 1 WHERE user_id = 5;


-- Company B
INSERT INTO companies (
    representative_user_id,
    company_name,
    industry,
    location,
    website_url,
    description,
    pr_message,
    logo_image_url,
    contact_email,
    contact_phone,
    approval_status,
    approved_by_admin_id,
    approved_at
) VALUES (
    6, -- Assuming Futami CompanyRep user_id is 6
    'Sample B Tech Solutions',
    'Technology',
    'Tokyo, Japan',
    'https://sampleB.example.com',
    'Developing innovative software for factory automation.',
    'Join our team of experts and work on cutting-edge projects.',
    'https://example.com/logos/sampleB.png',
    'info@sampleB.example.com',
    '03-9876-5432',
    'approved',
    1, -- Assuming Admin User ID is 1
    NOW()
);
-- Assume company_id for Sample B Tech Solutions is 2

-- Update users.company_id for Futami CompanyRep (user_id=6) with company_id for Sample B (company_id=2)
UPDATE users SET company_id = 2 WHERE user_id = 6;


-- 6. Sample Events (Optional - requires company_ids)
-- Assuming Sample A Manufacturing Co. has company_id = 1
-- Assuming Sample B Tech Solutions has company_id = 2

INSERT INTO events (
    company_id,
    title,
    description,
    event_datetime,
    duration_minutes,
    location_type,
    location_detail,
    capacity,
    application_deadline,
    is_published
) VALUES (
    1, -- Sample A Manufacturing Co.
    'Factory Tour and Info Session',
    'Come see our state-of-the-art facility and learn about opportunities.',
    (NOW() + INTERVAL '14 days'), -- Event in 14 days
    120,
    'offline',
    '123 Manufacturing Rd, Osaka',
    50,
    (NOW() + INTERVAL '10 days'), -- Deadline in 10 days
    TRUE
),
(
    2, -- Sample B Tech Solutions
    'Tech Talk: AI in Automation',
    'Join us for an online session on the future of AI in factory automation.',
    (NOW() + INTERVAL '21 days'), -- Event in 21 days
    90,
    'online',
    'https://meeting.example.com/techtalkB',
    100,
    (NOW() + INTERVAL '17 days'), -- Deadline in 17 days
    TRUE
);

-- 7. Sample Internship Applications (Optional - requires job_seeker_ids, company_ids, event_ids)
-- Assuming Hana Jobseeker (user_id=2), Jiro Jobseeker (user_id=3)
-- Assuming Sample A Manufacturing Co. (company_id=1), Event ID for Factory Tour (event_id=1)
-- Assuming Sample B Tech Solutions (company_id=2)

INSERT INTO internship_applications (
    job_seeker_id,
    company_id,
    event_id, -- Applied via the event
    status,
    application_datetime,
    preferred_start_date,
    message_to_company
) VALUES (
    2, -- Hana Jobseeker
    1, -- Sample A Manufacturing Co.
    1, -- Factory Tour and Info Session
    'applied',
    NOW(),
    (NOW() + INTERVAL '30 days')::DATE,
    'Very interested in your metalworking processes and would love the opportunity to learn more through an internship.'
),
(
    3, -- Jiro Jobseeker
    2, -- Sample B Tech Solutions
    NULL, -- Applied directly, not via an event
    'applied',
    NOW(),
    (NOW() + INTERVAL '45 days')::DATE,
    'Your work in AI and automation aligns perfectly with my interests. I have attached my resume for your consideration.'
);

-- 8. Sample Notifications (Optional - requires admin_user_id)
INSERT INTO notifications (
    title,
    content,
    target_user_type,
    published_at,
    created_by_admin_id -- Assuming Admin User ID is 1
) VALUES (
    'Welcome to the New Platform!',
    'We are excited to launch this platform to connect job seekers with great opportunities in manufacturing. Explore events and internships now!',
    'all',
    NOW(),
    1
),
(
    'New Internship Opportunities Available',
    'Several new companies have posted internship programs. Check the listings for details and apply today!',
    'job_seeker',
    NOW(),
    1
);

-- End of Initial Data Insertion
